### ISSUE TITLE
Contribute upstream?

### ISSUE THREAD

**Issue by begriffs** [mfine/heroku-buildpack-stack#1]
Great idea to use stack!

I've been meaning to modernize heroku-buildpack-ghc for some time because people still use it. Maybe you could send a pull request to get your changes out to those existing users?

**Comment by mfine** [comment]
Completely missed this... sorry about that! Definitely could bring this back upstream, but there were things I had to leave out in order to fit everything in under the size limits, and as a result this buildpack only ships the binaries :( I can re-look at it and see if there's anything to help out there.

**Comment by mfine** [comment]
Going to leave this as stack only for now.
