### ISSUE TITLE
Heroku Cache Not Updating

### ISSUE THREAD

**Issue by wjdhamilton** [mfine/heroku-buildpack-stack#34]
Thank you very much for coding this buildpack.

I can use the pack to deploy my yesod application correctly, but if I make any changes they are not overridden by the next deploy. I have to clear the repo cache and then rebuild the application from scratch to see my changes appear. 

Not sure how to go about debugging this either. Sorry! Any thoughts?

**Comment by mfine** [comment]
Hi @wjdhamilton! I'm trying to understand what your issue is - how are you making changes that are not getting picked up by the next deploy? The stack work directory is getting cached and restored if [possible](https://github.com/mfine/heroku-buildpack-stack/blob/master/bin/compile#L88) - I'm trying to understand how your changes would bypass the stack tool picking them up. The buildpack supports a makefile - you could remove the stack work directory there to achieve a similar impact - see [makefile-support](https://github.com/mfine/heroku-buildpack-stack#makefile-support).

**Comment by wjdhamilton** [comment]
Hmmm...I just tried to create an example for you and the damn thing worked properly! I'll close this and reopen it if the problem happens again. Sorry!
